// <auto-generated />
using System;
using AchievementsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AchievementsService.Data.Migrations
{
    [DbContext(typeof(AchievementsDbContext))]
    partial class AchievementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AchievementsService.Entities.Achievement", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Code");

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "FIRST_GAME",
                            Description = "Complete your first game.",
                            Name = "First Game",
                            TargetValue = 1,
                            Type = "one_time"
                        },
                        new
                        {
                            Code = "FIRST_WIN",
                            Description = "Win your first game.",
                            Name = "First Win",
                            TargetValue = 1,
                            Type = "one_time"
                        },
                        new
                        {
                            Code = "SCORE_500",
                            Description = "Reach 500 score in a single game.",
                            Name = "Score 500",
                            TargetValue = 500,
                            Type = "one_time"
                        },
                        new
                        {
                            Code = "SCORE_1000",
                            Description = "Reach 1000 score in a single game.",
                            Name = "Score 1000",
                            TargetValue = 1000,
                            Type = "one_time"
                        },
                        new
                        {
                            Code = "KILLS_10",
                            Description = "Make 10 kills in a single game.",
                            Name = "Kills 10",
                            TargetValue = 10,
                            Type = "one_time"
                        },
                        new
                        {
                            Code = "PERFECT_GAME",
                            Description = "Win a game with zero deaths.",
                            Name = "Perfect Game",
                            TargetValue = 1,
                            Type = "one_time"
                        },
                        new
                        {
                            Code = "PLAY_10_GAMES",
                            Description = "Play 10 games in total.",
                            Name = "Play 10 Games",
                            TargetValue = 10,
                            Type = "progressive"
                        },
                        new
                        {
                            Code = "WIN_5",
                            Description = "Win 5 games in total.",
                            Name = "Win 5 Games",
                            TargetValue = 5,
                            Type = "progressive"
                        },
                        new
                        {
                            Code = "TOTAL_SCORE_5000",
                            Description = "Accumulate 5000 score in total.",
                            Name = "Total Score 5000",
                            TargetValue = 5000,
                            Type = "progressive"
                        },
                        new
                        {
                            Code = "KILLS_100",
                            Description = "Accumulate 100 kills in total.",
                            Name = "Kills 100",
                            TargetValue = 100,
                            Type = "progressive"
                        });
                });

            modelBuilder.Entity("AchievementsService.Entities.ProcessedResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("ResultId");

                    b.ToTable("processed_results", (string)null);
                });

            modelBuilder.Entity("AchievementsService.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("achievement_code");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementCode");

                    b.HasIndex("UserId", "AchievementCode")
                        .IsUnique();

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("AchievementsService.Entities.UserStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("TotalKills")
                        .HasColumnType("integer")
                        .HasColumnName("total_kills");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("UserId");

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("AchievementsService.Entities.UserAchievement", b =>
                {
                    b.HasOne("AchievementsService.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });
#pragma warning restore 612, 618
        }
    }
}
